model:
  pretrained_weights: ''
  model_type: hrnet_w32
  num_keypoints: 17
resize:
  enabled: true
  long_side: 896
  keep_aspect_ratio: true
train:
  train_val_split: 0.9
  max_epochs: 150
  batch_size: 6
  learning_rate: 0.0005
  weight_decay: 0.0001
  num_workers: 12
  early_stop_patience: 10
augment:
  flip_augmentation: true
  rotation_augmentation_deg: 15
  rotation_augmentation_prob: 0.9
  scale_augmentation: 0.3
  scale_augmentation_prob: 0.8
  color_jitter:
    enabled: true
    prob: 0.4
    brightness: 0.1
    contrast: 0.1
    saturation: 0.05
data:
  heatmap_sigma_px: 4
infer:
  threshold: 0.2
